---
- name: playbook to install apache tomcat
  hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - tomcat_vars.yml

  tasks:
    - name: install java-1.8
      yum:
       name: java
       state: present

    - name: download tomcat packages
      get_url:
         url: "{{ tomcat_url}}"
         dest: /opt
         mode: 0755

    - name: extract packages
      unarchive:
        src: /opt/{{ tomcat_package }}.tar.gz
        dest: /opt
        remote_src: yes

    - name: change permissions on apache tomcat file
      file:
        path: /opt/{{ tomcat_package }}
        mode: 0755
        recurse: yes

    - name: creating link file for tomcat startup.sh
      file:
        src: /opt/{{ tomcat_package }}/bin/startup.sh
        dest: /usr/local/bin/tomcatup
        state: link

    - name: Creating link file for tomcat shutdown.sh
      file:
        src: /opt/{{ tomcat_package }}/bin/shutdown.sh
        dest: /usr/local/bin/tomcatdown
        state: link

    - name: start the service
      command: nohup ./startup.sh
      args:
        chdir: /opt/{{ tomcat_package }}/bin/
